import { getDb } from "./server/db";
import { treatments } from "./drizzle/schema";

// 마이그레이션할 데이터
const treatmentsData = [
  // ── Best 시술 ────────────────────────────────────────────
  {
    name: "울써마지 리프팅 + 리쥬란",
    nameEn: "ULTHERAPY + THERMAGE LIFT + REJURAN",
    categoryId: "best",
    desc: "리프팅의 끝판왕이라 불리는 울쎄라피+써마지 복합 리프팅에 피부 재생 리쥬란을 더한 프리미엄 프로그램.",
    time: "90~120분",
    recovery: "당일 일상",
    badge: "진정하 시술",
    badgeColor: "#4A6FA5",
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663496986810/4mEoPkvqQdPU4cZqm7AUEB/울쎄라피프라임_1_0daba485.png",
    cardBannerImage: "https://d2xsxph8kpxj0f.cloudfront.net/310519663496986810/4mEoPkvqQdPU4cZqm7AUEB/울쎄라피프라임_1_0daba485.png",
    best: true,
    detail: "울쎄라피 프라임의 집속 초음파(HIFU) 에너지가 SMAS층(근막층)까지 도달하여 피부 깊은 곳에서부터 리프팅 효과를 유도하고, 써마지 FLX의 고주파 에너지가 진피 콜라겐을 자극하여 피부 탄력을 개선합니다. 여기에 리쥬란 힐러(연어 DNA 성분)를 추가하여 피부 재생과 수분 보충을 동시에 제공하는 복합 프리미엄 프로그램입니다.",
    caution: "시술 후 당일 세안은 부드럽게 하고, 강한 마사지나 사우나는 1주일간 피하세요.",
    sessions: "1~2회 (6~12개월 간격)",
    effect: "얼굴 리프팅, 피부 탄력 개선, 주름 완화, 피부 재생, 수분 보충",
    youtubeUrl: "https://www.youtube.com/embed/vZ0rL_XAXUU",
    isActive: true,
  },
  {
    name: "볼륨업 프로그램",
    nameEn: "VOLUME UP PROGRAM · SCULPTRA",
    categoryId: "best",
    desc: "FDA 승인 스컬트라로 피부 스스로 콜라겐을 생성해 자연스러운 볼륨을 회복.",
    time: "30~60분",
    recovery: "당일 일상",
    badge: "2년 지속",
    badgeColor: "#9C5FA5",
    image: "https://d2xsxph8kpxj0f.cloudfront.net/104196446/FfraVpZBeN8JUDHaejFA3e/treat-sculptra_c3f4b5f6.png",
    cardBannerImage: "https://d2xsxph8kpxj0f.cloudfront.net/310519663496986810/4mEoPkvqQdPU4cZqm7AUEB/볼륨업프로그램_3442a94f.png",
    best: true,
    detail: "스컬트라(Sculptra)는 PLLA(폴리-L-락틱산) 성분의 생체 자극형 콜라겐 자극제입니다.",
    caution: "시술 후 5-5-5 마사지(하루 5회, 5분씩, 5일간)를 반드시 시행하세요.",
    sessions: "2~3회 (4~6주 간격)",
    effect: "볼 볼륨 회복, 팔자주름 개선, 피부 탄력 향상",
    youtubeUrl: "https://www.youtube.com/embed/J6EcnHsUYew",
    isActive: true,
  },
  {
    name: "줄기세포 치료",
    nameEn: "STEM CELL THERAPY",
    categoryId: "best",
    desc: "자신의 혈액·지방에서 추출한 줄기세포를 피부에 직접 주사하는 자가세포 치료.",
    time: "60~120분",
    recovery: "3~7일",
    badge: "자가세포",
    badgeColor: "#2E7D32",
    image: "https://d2xsxph8kpxj0f.cloudfront.net/104196446/FfraVpZBeN8JUDHaejFA3e/stemcell_treatment_card-oGb7XJiuyUVsc7VGWNioEw.webp",
    cardBannerImage: "https://d2xsxph8kpxj0f.cloudfront.net/310519663496986810/4mEoPkvqQdPU4cZqm7AUEB/줄기세포-치료_ff39fa9f.png",
    best: true,
    detail: "혈액 유래 줄기세포 치료는 소량의 혈액을 채취하여 원심분리 후 줄기세포 성분을 농축·분리하고 피부에 주사합니다.",
    caution: "시술 전 혈액 채취 또는 지방 채취 과정이 포함됩니다.",
    sessions: "1~3회 (담당 의료진 상담 후 결정)",
    effect: "피부 재생, 탄력 개선, 수분 보충, 피부결 정돈",
    modalImage: "https://d2xsxph8kpxj0f.cloudfront.net/310519663496986810/4mEoPkvqQdPU4cZqm7AUEB/줄기세포-치료_ff39fa9f.png",
    isActive: true,
  },
  {
    name: "흉터 치료 프로그램",
    nameEn: "ULTRAPULSE + DRT + MIRAJET + TRIFILL PRO",
    categoryId: "best",
    desc: "울트라펄스 레이저·DRT·미라젯·트리필프로를 결합한 흉터 집중 프로그램.",
    time: "60~90분",
    recovery: "5~7일",
    badge: "진정하 시술",
    badgeColor: "#81C7C9",
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663496986810/4mEoPkvqQdPU4cZqm7AUEB/equip-mcl31-ultrapulse_84704967.png",
    cardBannerImage: "https://d2xsxph8kpxj0f.cloudfront.net/310519663496986810/4mEoPkvqQdPU4cZqm7AUEB/흉터치료_d89a476f.png",
    best: true,
    detail: "울트라펄스 레이저로 흉터 표면을 정밀하게 제거하고, DRT(진피 리모델링 치료)로 진피층 콜라겐 재생을 유도합니다.",
    caution: "시술 후 5~7일간 피부 재생 기간이 필요합니다.",
    sessions: "3~5회 (4~6주 간격)",
    effect: "여드름 흉터 개선, 패인 흉터 볼륨 회복, 피부 재생",
    youtubeUrl: "https://www.youtube.com/embed/DFB4SZU5U-g",
    isActive: true,
  },
  {
    name: "홍조 치료 프로그램",
    nameEn: "ROSACEA PROGRAM · EXCEL V+ + ADVATX",
    categoryId: "best",
    desc: "Excel V+·ADVATX 듀얼 레이저로 안면홍조·모세혈관 확장을 전문 치료.",
    time: "20~40분",
    recovery: "1~2일",
    badge: "무상처 치료",
    badgeColor: "#E57373",
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663496986810/4mEoPkvqQdPU4cZqm7AUEB/엑셀V_70001aa7.png",
    cardBannerImage: "https://d2xsxph8kpxj0f.cloudfront.net/310519663496986810/4mEoPkvqQdPU4cZqm7AUEB/홍조치료_32fd1648.png",
    best: true,
    detail: "Excel V+의 532nm KTP 레이저는 혈관 내 헤모글로빈에 선택적으로 흡수되어 확장된 혈관을 피부 표면에 상처 없이 응고·폐쇄합니다.",
    caution: "시술 후 1~2일간 세안 시 자극을 최소화하고, 뜨거운 음식·음주·사우나는 피하세요.",
    sessions: "4~6회 (2~4주 간격)",
    effect: "안면홍조 개선, 모세혈관 확장 개선, 피부 톤 균일화",
    isActive: true,
  },
  // ── 리프팅 ────────────────────────────────────────────
  {
    name: "울써마지 리프팅",
    nameEn: "ULTHERAPY PRIME LIFTING",
    categoryId: "lifting",
    desc: "집속 초음파(HIFU)로 SMAS층까지 도달하여 피부 깊은 곳에서부터 리프팅하는 시술.",
    time: "60~90분",
    recovery: "당일 일상",
    badge: "진정하 시술",
    badgeColor: "#4A6FA5",
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663496986810/4mEoPkvqQdPU4cZqm7AUEB/울쎄라피프라임_1_0daba485.png",
    best: false,
    detail: "울쎄라피 프라임은 최신 세대의 집속 초음파 장비로, SMAS층(근막층)까지 정밀하게 에너지를 전달합니다.",
    caution: "시술 후 당일 세안은 부드럽게 하고, 강한 마사지나 사우나는 1주일간 피하세요.",
    sessions: "1~2회 (6~12개월 간격)",
    effect: "얼굴 리프팅, 피부 탄력 개선, 주름 완화",
    youtubeUrl: "https://www.youtube.com/embed/vZ0rL_XAXUU",
    isActive: true,
  },
  {
    name: "써마지 리프팅",
    nameEn: "THERMAGE FLX LIFTING",
    categoryId: "lifting",
    desc: "고주파 에너지로 진피 콜라겐을 자극하여 피부 탄력을 개선하는 비침습 리프팅.",
    time: "45~60분",
    recovery: "당일 일상",
    badge: "비침습",
    badgeColor: "#F59E0B",
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663496986810/4mEoPkvqQdPU4cZqm7AUEB/써마지FLX_20a90462.png",
    best: false,
    detail: "써마지 FLX는 고주파(RF) 에너지를 이용하여 진피층의 콜라겐을 가열·수축시키고, 장기적으로 새로운 콜라겐 생성을 유도합니다.",
    caution: "시술 후 1~2일간 경미한 붓기나 열감이 있을 수 있습니다.",
    sessions: "1회 (필요시 6~12개월 후 재시술)",
    effect: "피부 탄력 개선, 주름 완화, 얼굴 리프팅",
    isActive: true,
  },
  {
    name: "리쥬란 힐러",
    nameEn: "REJURAN HEALER",
    categoryId: "lifting",
    desc: "연어 DNA 성분으로 피부 재생과 탄력을 동시에 개선하는 시술.",
    time: "30~45분",
    recovery: "당일 일상",
    badge: "DNA 재생",
    badgeColor: "#10B981",
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663496986810/4mEoPkvqQdPU4cZqm7AUEB/리쥬란_힐러_d4e4c5f1.png",
    best: false,
    detail: "리쥬란 힐러는 연어 정소에서 추출한 폴리뉴클레오타이드(PN) 성분을 피부에 주입하여 세포 재생을 촉진합니다.",
    caution: "시술 후 24시간 동안 세안과 화장은 피하고, 3~7일간 붓기가 있을 수 있습니다.",
    sessions: "4~6회 (1~2주 간격)",
    effect: "피부 재생, 탄력 개선, 수분 보충, 피부결 정돈",
    isActive: true,
  },
  // ── 주름개선 ────────────────────────────────────────────
  {
    name: "보톡스",
    nameEn: "BOTOX",
    categoryId: "wrinkle",
    desc: "주름 개선과 얼굴 윤곽 교정에 효과적인 시술입니다.",
    time: "10~15분",
    recovery: "당일 일상",
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663496986810/4mEoPkvqQdPU4cZqm7AUEB/보톡스_필러_8f9e3c2d.png",
    best: false,
    detail: "보톡스는 신경 전달 물질을 차단하여 표정근의 수축을 완화시킴으로써 주름을 개선합니다.",
    caution: "시술 후 4시간 동안 눕거나 누워있지 마세요. 효과는 3~7일 후부터 나타나며 2주 후 최대 효과를 보입니다.",
    sessions: "3~4개월마다 1회",
    effect: "주름 개선, 얼굴 윤곽 교정, 표정 개선",
    isActive: true,
  },
  {
    name: "필러",
    nameEn: "FILLER",
    categoryId: "wrinkle",
    desc: "히알루론산 필러로 주름을 채우고 볼륨을 더하는 시술.",
    time: "20~30분",
    recovery: "당일 일상",
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663496986810/4mEoPkvqQdPU4cZqm7AUEB/필러_a2b3c4d5.png",
    best: false,
    detail: "히알루론산 필러는 피부 내 주름 부위에 주입하여 즉각적인 볼륨 효과를 제공합니다.",
    caution: "시술 후 3~7일간 붓기와 멍이 나타날 수 있습니다.",
    sessions: "6~12개월마다 1회",
    effect: "주름 개선, 볼륨 증가, 얼굴 윤곽 개선",
    isActive: true,
  },
  // ── 톤개선 ────────────────────────────────────────────
  {
    name: "색소 치료",
    nameEn: "PIGMENTATION TREATMENT",
    categoryId: "skin_tone",
    desc: "레이저로 색소 침착을 제거하고 피부톤을 균일하게 개선하는 시술.",
    time: "20~40분",
    recovery: "3~5일",
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663496986810/4mEoPkvqQdPU4cZqm7AUEB/색소치료_e5f6g7h8.png",
    best: false,
    detail: "다양한 파장의 레이저를 사용하여 멜라닌 색소를 선택적으로 제거합니다.",
    caution: "시술 후 3~5일간 딱지가 생길 수 있으며, 자외선 차단이 필수입니다.",
    sessions: "3~5회 (2~4주 간격)",
    effect: "기미 개선, 주근깨 제거, 피부톤 균일화",
    isActive: true,
  },
  // ── 흉터치료 ────────────────────────────────────────────
  {
    name: "여드름 흉터 치료",
    nameEn: "ACNE SCAR TREATMENT",
    categoryId: "scar",
    desc: "울트라펄스 레이저로 여드름 흉터를 효과적으로 개선합니다.",
    time: "30~60분",
    recovery: "5~7일",
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663496986810/4mEoPkvqQdPU4cZqm7AUEB/여드름흉터_i9j0k1l2.png",
    best: false,
    detail: "울트라펄스 레이저는 흉터 표면을 정밀하게 제거하고 콜라겐 재생을 유도합니다.",
    caution: "시술 후 5~7일간 피부 재생 기간이 필요합니다.",
    sessions: "3~5회 (4~6주 간격)",
    effect: "여드름 흉터 개선, 피부 재생, 콜라겐 생성",
    isActive: true,
  },
  // ── 백반증 ────────────────────────────────────────────
  {
    name: "전신 자외선 광선 치료기",
    nameEn: "FULL BODY UV THERAPY",
    categoryId: "vitiligo",
    desc: "전신 자외선 광선 치료로 백반증을 개선합니다.",
    time: "15~30분",
    recovery: "당일 일상",
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663496986810/4mEoPkvqQdPU4cZqm7AUEB/전신자외선_m3n4o5p6.png",
    best: false,
    detail: "자외선 광선 치료는 백반증 부위의 멜라닌 생성을 촉진합니다.",
    caution: "정기적인 치료가 필요하며, 개인차에 따라 효과가 다릅니다.",
    sessions: "주 2~3회 (장기 치료)",
    effect: "백반증 개선, 색소 회복, 피부톤 균일화",
    youtubeUrl: "https://www.youtube.com/embed/RuJSEpsvy_Q",
    isActive: true,
  },
  // ── 문신제거 ────────────────────────────────────────────
  {
    name: "문신 제거",
    nameEn: "TATTOO REMOVAL",
    categoryId: "tattoo",
    desc: "레이저로 문신을 안전하게 제거합니다.",
    time: "20~60분",
    recovery: "1~2주",
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663496986810/4mEoPkvqQdPU4cZqm7AUEB/문신제거_q7r8s9t0.png",
    best: false,
    detail: "다양한 파장의 레이저를 사용하여 문신 색소를 선택적으로 제거합니다.",
    caution: "시술 후 1~2주간 붓기와 딱지가 생길 수 있습니다.",
    sessions: "여러 회 (색상과 크기에 따라 다름)",
    effect: "문신 제거, 색소 제거",
    isActive: true,
  },
];

async function migrate() {
  try {
    console.log("마이그레이션 시작...");
    const db = await getDb();
    
    // 기존 데이터 삭제 (옵션)
    // await db.delete(treatments).execute();
    
    // 데이터 삽입
    for (const treatment of treatmentsData) {
      await db.insert(treatments).values({
        ...treatment,
        images: null,
        imgBg: null,
        related: null,
        steps: null,
        modalImage: treatment.modalImage || null,
        best: treatment.best ? "1" : "0",
        isActive: treatment.isActive ? "1" : "0",
      }).execute();
    }
    
    console.log(`✅ ${treatmentsData.length}개의 시술 데이터 마이그레이션 완료!`);
  } catch (error) {
    console.error("❌ 마이그레이션 실패:", error);
    process.exit(1);
  }
}

migrate();
