CREATE TABLE `events` (
	`id` int AUTO_INCREMENT NOT NULL,
	`type` enum('이벤트','공지') NOT NULL DEFAULT '이벤트',
	`title` varchar(200) NOT NULL,
	`subtitle` varchar(150) NOT NULL DEFAULT '',
	`desc` text NOT NULL,
	`content` text NOT NULL DEFAULT (''),
	`isFeatured` enum('0','1') NOT NULL DEFAULT '0',
	`badge` varchar(50) NOT NULL DEFAULT '',
	`tag` varchar(50) NOT NULL DEFAULT '',
	`hot` enum('0','1') NOT NULL DEFAULT '0',
	`cta` varchar(50) NOT NULL DEFAULT '자세히 보기',
	`accent` varchar(20) NOT NULL DEFAULT '#4A6FA5',
	`accentDark` varchar(20) NOT NULL DEFAULT '#2D4A7B',
	`accentBg` varchar(20) NOT NULL DEFAULT '#EEF3FA',
	`iconBg` varchar(20) NOT NULL DEFAULT '#E0EBF7',
	`iconType` varchar(20) NOT NULL DEFAULT 'tag',
	`badgeColor` varchar(20) NOT NULL DEFAULT '#4A6FA5',
	`imageUrl` text,
	`date` varchar(50) NOT NULL,
	`views` int NOT NULL DEFAULT 0,
	`sortOrder` int NOT NULL DEFAULT 0,
	`isActive` enum('0','1') NOT NULL DEFAULT '1',
	`category` enum('신규시술','이벤트','공지사항','기타') NOT NULL DEFAULT '이벤트',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `events_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `popupEvents` (
	`id` int AUTO_INCREMENT NOT NULL,
	`tab` varchar(50) NOT NULL,
	`badge` varchar(100) NOT NULL,
	`title` varchar(100) NOT NULL,
	`subtitle` varchar(100) NOT NULL DEFAULT '',
	`desc` text NOT NULL DEFAULT (''),
	`priceItems` text NOT NULL DEFAULT ('[]'),
	`note` varchar(200) NOT NULL DEFAULT '',
	`imageUrl` text,
	`accent` varchar(20) NOT NULL DEFAULT '#4A6FA5',
	`accentLight` varchar(20) NOT NULL DEFAULT '#EEF4FF',
	`startAt` bigint,
	`endAt` bigint,
	`sortOrder` int NOT NULL DEFAULT 0,
	`isActive` enum('0','1') NOT NULL DEFAULT '1',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `popupEvents_id` PRIMARY KEY(`id`)
);
