ALTER TABLE `treatments` ADD `nameJa` varchar(200) DEFAULT '';--> statement-breakpoint
ALTER TABLE `treatments` ADD `nameZh` varchar(200) DEFAULT '';--> statement-breakpoint
ALTER TABLE `treatments` ADD `descEn` text DEFAULT ('');--> statement-breakpoint
ALTER TABLE `treatments` ADD `descJa` text DEFAULT ('');--> statement-breakpoint
ALTER TABLE `treatments` ADD `descZh` text DEFAULT ('');--> statement-breakpoint
ALTER TABLE `treatments` ADD `timeEn` varchar(50) DEFAULT '';--> statement-breakpoint
ALTER TABLE `treatments` ADD `timeJa` varchar(50) DEFAULT '';--> statement-breakpoint
ALTER TABLE `treatments` ADD `timeZh` varchar(50) DEFAULT '';--> statement-breakpoint
ALTER TABLE `treatments` ADD `recoveryEn` varchar(50) DEFAULT '';--> statement-breakpoint
ALTER TABLE `treatments` ADD `recoveryJa` varchar(50) DEFAULT '';--> statement-breakpoint
ALTER TABLE `treatments` ADD `recoveryZh` varchar(50) DEFAULT '';--> statement-breakpoint
ALTER TABLE `treatments` ADD `badgeEn` varchar(100) DEFAULT '';--> statement-breakpoint
ALTER TABLE `treatments` ADD `badgeJa` varchar(100) DEFAULT '';--> statement-breakpoint
ALTER TABLE `treatments` ADD `badgeZh` varchar(100) DEFAULT '';--> statement-breakpoint
ALTER TABLE `treatments` ADD `detailEn` text DEFAULT ('');--> statement-breakpoint
ALTER TABLE `treatments` ADD `detailJa` text DEFAULT ('');--> statement-breakpoint
ALTER TABLE `treatments` ADD `detailZh` text DEFAULT ('');--> statement-breakpoint
ALTER TABLE `treatments` ADD `cautionEn` text DEFAULT ('');--> statement-breakpoint
ALTER TABLE `treatments` ADD `cautionJa` text DEFAULT ('');--> statement-breakpoint
ALTER TABLE `treatments` ADD `cautionZh` text DEFAULT ('');--> statement-breakpoint
ALTER TABLE `treatments` ADD `sessionsEn` varchar(200) DEFAULT '';--> statement-breakpoint
ALTER TABLE `treatments` ADD `sessionsJa` varchar(200) DEFAULT '';--> statement-breakpoint
ALTER TABLE `treatments` ADD `sessionsZh` varchar(200) DEFAULT '';--> statement-breakpoint
ALTER TABLE `treatments` ADD `effectEn` text DEFAULT ('');--> statement-breakpoint
ALTER TABLE `treatments` ADD `effectJa` text DEFAULT ('');--> statement-breakpoint
ALTER TABLE `treatments` ADD `effectZh` text DEFAULT ('');--> statement-breakpoint
ALTER TABLE `treatments` ADD `slugEn` varchar(200) DEFAULT '';--> statement-breakpoint
ALTER TABLE `treatments` ADD `slugJa` varchar(200) DEFAULT '';--> statement-breakpoint
ALTER TABLE `treatments` ADD `slugZh` varchar(200) DEFAULT '';