CREATE TABLE `equipment3` (
	`id` int AUTO_INCREMENT NOT NULL,
	`slug` varchar(200) NOT NULL,
	`name` varchar(200) NOT NULL,
	`nameEn` varchar(200) NOT NULL DEFAULT '',
	`nameJa` varchar(200) DEFAULT '',
	`nameZh` varchar(200) DEFAULT '',
	`category` varchar(100) NOT NULL DEFAULT '',
	`categoryEn` varchar(100) DEFAULT '',
	`categoryJa` varchar(100) DEFAULT '',
	`categoryZh` varchar(100) DEFAULT '',
	`desc` text NOT NULL DEFAULT (''),
	`descEn` text DEFAULT (''),
	`descJa` text DEFAULT (''),
	`descZh` text DEFAULT (''),
	`detail` text DEFAULT (''),
	`detailEn` text DEFAULT (''),
	`detailJa` text DEFAULT (''),
	`detailZh` text DEFAULT (''),
	`effect` text DEFAULT (''),
	`effectEn` text DEFAULT (''),
	`effectJa` text DEFAULT (''),
	`effectZh` text DEFAULT (''),
	`caution` text DEFAULT (''),
	`cautionEn` text DEFAULT (''),
	`cautionJa` text DEFAULT (''),
	`cautionZh` text DEFAULT (''),
	`sessions` varchar(200) DEFAULT '',
	`sessionsEn` varchar(200) DEFAULT '',
	`sessionsJa` varchar(200) DEFAULT '',
	`sessionsZh` varchar(200) DEFAULT '',
	`time` varchar(50) DEFAULT '',
	`timeEn` varchar(50) DEFAULT '',
	`timeJa` varchar(50) DEFAULT '',
	`timeZh` varchar(50) DEFAULT '',
	`recovery` varchar(50) DEFAULT '',
	`recoveryEn` varchar(50) DEFAULT '',
	`recoveryJa` varchar(50) DEFAULT '',
	`recoveryZh` varchar(50) DEFAULT '',
	`imageUrl` text,
	`images` text DEFAULT ('[]'),
	`youtubeUrl` text,
	`modalImage` text,
	`badge` varchar(100) DEFAULT '',
	`badgeColor` varchar(20) DEFAULT '#4A6FA5',
	`sortOrder` int NOT NULL DEFAULT 0,
	`isActive` enum('0','1') NOT NULL DEFAULT '1',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `equipment3_id` PRIMARY KEY(`id`),
	CONSTRAINT `equipment3_slug_unique` UNIQUE(`slug`)
);
