import type { Lang } from "@/lib/i18n";
import type { UltherapyPrimeCopy } from "./ultherapyPrimeContent";

export type ThermageFlxCopy = UltherapyPrimeCopy & {
  tipTitle: string;
  tips: readonly [
    { name: string; area: string; description: string },
    { name: string; area: string; description: string },
  ];
  directorCaption: string;
};

const EMPTY_VIDEO_COPY = {
  shortsTitle: "",
  shortsAriaLabel: "",
  playVideoLabel: "",
  qaTitle: "",
  watchYoutubeLabel: "",
} as const;

export const THERMAGE_FLX_COPY: Record<Lang, ThermageFlxCopy> = {
  ko: {
    trustTitles: ["써마지 FLX 정품팁", "FDA & MFDS 승인", "피부과 전문의 진료"],
    trustSubtitles: ["100% 정품팁만 사용", "장비 관련 허가 정보", "믿고 안전하게 !"],
    mobileControlUnitAlt: "",
    heroTitle: "4세대에 걸친 진화된 써마지 FLX로 리프팅을 넘어 강력한 타이트닝 효과까지",
    heroDescription: "부산 서면 스타피부과에서 정품 써마지 FLX를 경험하세요!",
    whatTitle: "써마지 FLX는 어떤 시술인가요?",
    whatParagraphs: [
      "미국 FDA 승인을 받은 솔타사의 단극성 고주파 장비로 기존 3세대에서 진화한 써마지 FLX는 고주파 열에너지를 이용해 피부 진피층 콜라겐 섬유의 변성 및 수축을 일으켜 콜라겐 재생 및 탄력, 주름 개선 효과를 나타냅니다.",
      "",
    ],
    depthTitle: "고주파 에너지 전달 과정",
    depthText: "피부 상태를 확인한 뒤, 접촉면의 냉각과 함께 고주파 에너지를 전달합니다. 세부 계획과 반응은 개인 상태에 따라 달라질 수 있습니다.",
    authTitle: "써마지 FLX, 정품 팁을 확인하는 이유",
    authParagraphs: [
      "써마지 FLX 시술에서는 부위와 범위에 맞는 팁의 선택 및 장비 접촉 상태를 함께 확인합니다. 시술 전 개인 피부 상태와 관리 목표를 충분히 상담하는 과정이 필요합니다.",
      "스타피부과는 시술 시 1회용 정품 팁을 사용합니다.",
    ],
    authCaption: "식별 라벨이 부착된 써마지 FLX 정품 팁 패키지",
    collagenTitle: "콜라겐 재생 촉진과 리프팅을 동시에!",
    collagenStages: ["피부 상태와 목표 부위 확인", "고주파 에너지 전달", "개인별 회복 과정"],
    collagenNote: "표피를 냉각시키고 진피 조직에 열을 발생시키는 원리를 사용해 고주파 에너지를 전달함으로써 콜라겐 섬유의 변성 및 수축을 일으켜 콜라겐 재생이 이루어지면서 피부 탄력 개선에 도움을 줍니다.",
    processTitle: "써마지 FLX의 세 가지 특징",
    processDescriptions: ["토탈팁 4.0㎠로 얼굴 부위의 시술 범위를 계획", "개인 피부 상태를 고려해 에너지 전달을 계획", "쿨링·진동 기능으로 시술 중 불편감 관리에 도움"],
    processNote: "시술 부위와 팁, 에너지 설정은 피부 상태와 관리 목표를 확인한 뒤 개인별로 계획합니다.",
    painTitle: "써마지 FLX, 통증때문에 고민이라면?",
    painOptions: ["마취크림", "국소마취주사", "수면마취"],
    painParagraphs: [
      "스타피부과는 통증케어 시스템(마취크림, 국소마취주사)을 통해 통증을 줄이고, 보다 통증에 민감하신 경우 선택적인 수면마취 시스템까지 제공하고 있어 높은 효율의 편안한 시술이 가능합니다.",
      "특히 수면마취는 시술 통증을 줄이고, 환자의 긴장감과 불안함을 해소하여 편안한 상태에서 시술 받을 수 있다는 장점이 있습니다.",
    ],
    combinationTitle: "써마지 FLX와 함께 고려할 수 있는 시술",
    combinationTitles: ["써마지 FLX + 울쎄라피 프라임", "써마지 FLX + 슈링크 유니버스", "써마지 FLX + 온다 + 브이로", "써마지 FLX + 루메니스원 + 리쥬란", "써마지 FLX + 스킨보톡스"],
    combinationBadges: ["", "", "", "", ""],
    combinationDescriptions: [
      "고주파와 초음파 장비의 특성을 함께 고려해 피부 상태와 관리 목표에 맞춰 상담할 수 있는 조합",
      "피부 고민과 예산, 관리 범위를 함께 고려해 상담할 수 있는 리프팅 조합",
      "이중턱·심부볼·볼 처짐 등 고민 부위를 바탕으로 상담할 수 있는 복합 관리 조합",
      "피부 컨디션과 관리 목표에 따라 함께 고려할 수 있는 피부 탄력·컨디션 관리 조합",
      "피부결과 표정 주름 등 개별적인 피부 고민을 함께 상담할 수 있는 조합",
    ],
    recommendTitle: "써마지 FLX, 이런 분께 추천합니다",
    recommendations: ["수술적 접근 없이 피부 탄력 관리를 고려하는 분", "얼굴·눈가·목 부위의 탄력 고민을 상담하고 싶은 분", "모공·피부결 등 복합적인 피부 고민을 상담하고 싶은 분", "시술 후 일상 복귀 가능 여부를 상담하고 싶은 분", "개인 피부 상태에 맞는 리프팅 계획을 세우고 싶은 분"],
    areasCaption: "써마지 FLX 시술 가능 부위",
    starTitle: "피부 상태를 바탕으로, 스타피부과가 함께 계획합니다",
    starIntro: "스타피부과는 개인별 피부 타입과 얼굴형, 고민 부위와 관리 목표를 살펴보고 시술 부위와 범위를 신중하게 계획합니다.",
    strengths: ["피부과 전문의\n진료", "20년 이상의\n임상 경험", "1:1 체계적인\n맞춤 플랜", "다양한 리프팅\n장비 보유"],
    certificationTitle: "써마지 FLX 정품 팁 사용",
    certificationText: "스타피부과는 시술 시 1회용 정품 팁을 사용합니다.",
    tipTitle: "얼굴부터 눈가주름까지 부위별 집중 케어",
    tips: [
      { name: "토탈팁 4.0㎠", area: "페이스 전용", description: "얼굴 부위의 관리 범위와 피부 상태를 고려해 사용하는 팁입니다." },
      { name: "아이팁 0.25㎠", area: "눈가 전용", description: "눈가처럼 세밀한 부위를 고려해 사용하는 전용 팁입니다." },
    ],
    directorCaption: "써마지 FLX 임상자문의 조시형 원장",
    ...EMPTY_VIDEO_COPY,
  },
  en: {
    trustTitles: ["Single-use authentic tip", "FDA & MFDS-cleared device", "Dermatologist-led care"],
    trustSubtitles: ["Opened for each treatment", "Device clearance information", "Planned for individual needs"],
    mobileControlUnitAlt: "",
    heroTitle: "Thermage FLX supports skin-firmness care with radiofrequency energy",
    heroDescription: "At STAR Dermatology in Seomyeon, Busan, Thermage FLX consultation and treatment are planned around each person’s skin condition.",
    whatTitle: "What Is Thermage FLX?",
    whatParagraphs: [
      "Thermage FLX is a device designed to support skin-firmness care by delivering radiofrequency (RF) energy to the skin. The treatment approach is determined after consultation based on the area and the individual’s skin condition.",
      "Cooling and vibration functions are used together, while the tip type and treatment range are planned by the medical team according to areas such as the face, eye area, and neck.",
    ],
    depthTitle: "How Radiofrequency Energy Is Delivered",
    depthText: "After assessing skin condition, radiofrequency energy is delivered with surface cooling. The detailed plan and response can vary by individual condition.",
    authTitle: "Why Check Authentic Thermage FLX Tips?",
    authParagraphs: [
      "For Thermage FLX, the choice of tip and device contact are reviewed according to the treatment area and range. A thorough consultation on skin condition and treatment goals is necessary before treatment.",
      "STAR Dermatology uses a single-use authentic tip for treatment.",
    ],
    authCaption: "An authentic Thermage FLX tip package with an identification label",
    collagenTitle: "Collagen Remodeling After Radiofrequency Energy",
    collagenStages: ["Review skin condition and target areas", "Deliver radiofrequency energy", "Individual recovery process"],
    collagenNote: "Skin changes and duration can vary according to individual skin condition, treatment range, and plan. A medical consultation is required before deciding on treatment.",
    processTitle: "Three Thermage FLX Features",
    processDescriptions: ["Plan treatment coverage for the face with the 4.0 cm² Total Tip", "Plan energy delivery with individual skin condition in mind", "Cooling and vibration functions help manage discomfort during treatment"],
    processNote: "Treatment areas, tips, and energy settings are planned individually after assessing skin condition and care goals.",
    painTitle: "Considering Thermage FLX Pain Management?",
    painOptions: ["Topical anesthetic cream", "Local anesthetic injection", "Sedation"],
    painParagraphs: ["Depending on pain sensitivity and treatment range, topical anesthetic cream, local anesthetic injection, or sedation can be selected after consultation.", "Whether sedation is appropriate is determined based on individual condition and medical judgment. Sufficient consultation and guidance are required before treatment."],
    combinationTitle: "Treatments That May Be Considered with Thermage FLX",
    combinationTitles: ["Thermage FLX + Ultherapy Prime", "Thermage FLX + Shurink Universe", "Thermage FLX + ONDA + V-RO", "Thermage FLX + Lumenis One + Rejuran", "Thermage FLX + Skin Botox"],
    combinationBadges: ["", "", "", "", ""],
    combinationDescriptions: ["A combination that can be discussed by considering the characteristics of RF and ultrasound devices alongside skin condition and care goals.", "A lifting combination that can be discussed with skin concerns, budget, and treatment scope in mind.", "A combined-care option that can be discussed based on concerns such as a double chin, deep cheek area, or cheek laxity.", "A pairing that can be considered according to skin condition and goals for firmness and skin-condition care.", "A pairing that can be discussed for individual concerns such as skin texture and expression lines."],
    recommendTitle: "Who May Consider Thermage FLX?",
    recommendations: ["Those considering skin-firmness care without a surgical approach", "Those wishing to discuss firmness concerns around the face, eye area, or neck", "Those wishing to discuss combined concerns such as pores and skin texture", "Those wishing to discuss whether same-day return to daily activities is appropriate", "Those seeking a lifting plan based on individual skin condition"],
    areasCaption: "Areas That May Be Treated with Thermage FLX",
    starTitle: "STAR Dermatology Plans Care Around Your Skin Condition",
    starIntro: "STAR Dermatology reviews individual skin type, facial shape, areas of concern, and care goals to thoughtfully plan the treatment area and range.",
    strengths: ["Board-certified\ndermatologist care", "More than 20 years of\nclinical experience", "Systematic one-to-one\ncustomized planning", "A range of\nlifting devices"],
    certificationTitle: "Thermage FLX Authentic Tip Use",
    certificationText: "STAR Dermatology uses a single-use authentic tip for treatment.",
    tipTitle: "Thermage FLX Tips Selected by Treatment Area",
    tips: [
      { name: "Total Tip 4.0 cm²", area: "For the face", description: "A tip used with the treatment range and skin condition of the face in mind." },
      { name: "Eye Tip 0.25 cm²", area: "For the eye area", description: "A dedicated tip used for detailed areas such as around the eyes." },
    ],
    directorCaption: "Thermage FLX Clinical Advisor, Dr. Cho Si-hyung",
    ...EMPTY_VIDEO_COPY,
  },
  ja: {
    trustTitles: ["使い捨て正規チップ使用", "FDA・MFDS許可機器", "皮膚科専門医による診療"],
    trustSubtitles: ["施術ごとに開封する正規チップ", "機器に関する許可情報", "お一人おひとりに合わせた計画"],
    mobileControlUnitAlt: "",
    heroTitle: "高周波エネルギーで肌のハリケアをサポートするThermage FLX",
    heroDescription: "釜山・西面のSTAR皮膚科では、肌状態に合わせてThermage FLXの相談と施術を行います。",
    whatTitle: "Thermage FLXとはどのような施術ですか？",
    whatParagraphs: ["Thermage FLXは、皮膚に高周波（RF）エネルギーを届け、肌のハリケアをサポートするために設計された機器です。施術部位と肌状態に応じて、相談後に施術方法を決定します。", "冷却と振動機能を併用し、顔・目元・首などの目的に合わせて、チップの種類と施術範囲を医療スタッフが計画します。"],
    depthTitle: "高周波エネルギーの伝達プロセス",
    depthText: "肌状態を確認したうえで、接触面を冷却しながら高周波エネルギーを届けます。詳細な計画や反応には個人差があります。",
    authTitle: "Thermage FLXで正規チップを確認する理由",
    authParagraphs: ["Thermage FLXでは、施術部位と範囲に合わせてチップの選択や機器の接触状態を確認します。施術前には、肌状態とケアの目標について十分な相談が必要です。", "STAR皮膚科では、施術時に使い捨ての正規チップを使用しています。"],
    authCaption: "識別ラベルが付いたThermage FLX正規チップのパッケージ",
    collagenTitle: "高周波エネルギー後のコラーゲンリモデリング過程",
    collagenStages: ["肌状態と目標部位を確認", "高周波エネルギーを伝達", "個人ごとの回復過程"],
    collagenNote: "肌の変化や持続期間は、肌状態、施術範囲、計画によって異なります。施術は医療スタッフとの相談後に決定します。",
    processTitle: "Thermage FLXの3つの特徴",
    processDescriptions: ["4.0cm²のトータルチップで顔の施術範囲を計画", "個々の肌状態を考慮してエネルギー伝達を計画", "冷却・振動機能で施術中の不快感管理をサポート"],
    processNote: "施術部位、チップ、エネルギー設定は、肌状態とケア目標を確認したうえで個別に計画します。",
    painTitle: "Thermage FLXの痛み管理が気になる方へ",
    painOptions: ["麻酔クリーム", "局所麻酔注射", "鎮静麻酔"],
    painParagraphs: ["痛みへの感受性と施術範囲に応じて、麻酔クリーム、局所麻酔注射、鎮静麻酔を相談後に選択できます。", "鎮静管理を含む対応は、個人の状態と医療スタッフの判断により実施の可否を決定します。施術前に十分な説明と相談が必要です。"],
    combinationTitle: "Thermage FLXとあわせて検討できる施術",
    combinationTitles: ["Thermage FLX + Ultherapy Prime", "Thermage FLX + Shurink Universe", "Thermage FLX + ONDA + V-RO", "Thermage FLX + Lumenis One + Rejuran", "Thermage FLX + スキンボトックス"],
    combinationBadges: ["", "", "", "", ""],
    combinationDescriptions: ["高周波と超音波機器の特徴を、肌状態とケア目標に合わせて相談できる組み合わせです。", "肌悩み、予算、施術範囲を考慮して相談できるリフティングの組み合わせです。", "二重あご、頬深部、頬のたるみなどの悩みに合わせて相談できる複合ケアです。", "肌コンディションとハリ・肌状態ケアの目標に応じて検討できる組み合わせです。", "肌理や表情じわなど、個別の肌悩みをあわせて相談できる組み合わせです。"],
    recommendTitle: "Thermage FLXはこのような方におすすめです",
    recommendations: ["手術的なアプローチをせず肌のハリケアを検討したい方", "顔・目元・首まわりのハリの悩みを相談したい方", "毛穴や肌理など複合的な肌悩みを相談したい方", "施術後の日常生活への復帰可否を相談したい方", "肌状態に合わせたリフティング計画を立てたい方"],
    areasCaption: "Thermage FLXの施術可能部位",
    starTitle: "肌状態をもとに、STAR皮膚科が一緒に計画します",
    starIntro: "STAR皮膚科は、お一人おひとりの肌質、顔立ち、悩みの部位、ケア目標を確認し、施術部位と範囲を慎重に計画します。",
    strengths: ["皮膚科専門医による\n診療", "20年以上の\n臨床経験", "1対1の体系的な\nカスタムプラン", "多様なリフティング\n機器を保有"],
    certificationTitle: "Thermage FLX正規チップ使用",
    certificationText: "STAR皮膚科では、施術時に使い捨ての正規チップを使用しています。",
    tipTitle: "部位に応じて選択するThermage FLXチップ",
    tips: [{ name: "トータルチップ 4.0cm²", area: "顔専用", description: "顔の施術範囲と肌状態を考慮して使用するチップです。" }, { name: "アイチップ 0.25cm²", area: "目元専用", description: "目元のような細かな部位に使用する専用チップです。" }],
    directorCaption: "Thermage FLX臨床顧問 チョ・シヒョン院長",
    ...EMPTY_VIDEO_COPY,
  },
  zh: {
    trustTitles: ["使用一次性原装治疗头", "FDA·MFDS许可设备", "皮肤科专科医师诊疗"],
    trustSubtitles: ["每次治疗前开封", "设备许可信息", "按个人状态制定计划"],
    mobileControlUnitAlt: "",
    heroTitle: "通过射频能量帮助进行皮肤紧致管理的Thermage FLX",
    heroDescription: "釜山西面STAR皮肤科会根据个人皮肤状态，进行Thermage FLX咨询与治疗规划。",
    whatTitle: "Thermage FLX是什么治疗？",
    whatParagraphs: ["Thermage FLX是一种通过向皮肤传递射频（RF）能量、帮助进行皮肤紧致管理的设备。治疗方式会根据部位与个人皮肤状态，在咨询后决定。", "治疗中会结合冷却与振动功能，治疗头种类和治疗范围由医疗团队根据面部、眼周、颈部等管理目的进行规划。"],
    depthTitle: "射频能量传递过程",
    depthText: "确认皮肤状态后，在接触面冷却的同时传递射频能量。详细计划与反应可能因个人状态而异。",
    authTitle: "为何需要确认Thermage FLX原装治疗头？",
    authParagraphs: ["Thermage FLX治疗会根据治疗部位和范围确认治疗头选择及设备接触状态。治疗前需要充分咨询皮肤状态和管理目标。", "STAR皮肤科在治疗时使用一次性原装治疗头。"],
    authCaption: "附有识别标签的Thermage FLX原装治疗头包装",
    collagenTitle: "射频能量后的胶原重塑过程",
    collagenStages: ["确认皮肤状态和目标部位", "传递射频能量", "个体化恢复过程"],
    collagenNote: "皮肤变化和维持时间会因个人皮肤状态、治疗范围和方案而有所不同，应在医疗咨询后决定。",
    processTitle: "Thermage FLX的三项特点",
    processDescriptions: ["以4.0cm²全效治疗头规划面部治疗范围", "结合个人皮肤状态规划能量传递", "冷却与振动功能有助于管理治疗中的不适"],
    processNote: "治疗部位、治疗头和能量设置会在确认皮肤状态与管理目标后进行个性化规划。",
    painTitle: "担心Thermage FLX的疼痛管理？",
    painOptions: ["麻醉膏", "局部麻醉注射", "镇静麻醉"],
    painParagraphs: ["可根据疼痛敏感度和治疗范围，在咨询后选择麻醉膏、局部麻醉注射或镇静麻醉。", "包括镇静在内的管理是否进行，需根据个人状态和医疗团队判断决定。治疗前需要充分说明和咨询。"],
    combinationTitle: "可与Thermage FLX一同考虑的治疗",
    combinationTitles: ["Thermage FLX + Ultherapy Prime", "Thermage FLX + Shurink Universe", "Thermage FLX + ONDA + V-RO", "Thermage FLX + Lumenis One + Rejuran", "Thermage FLX + Skin Botox"],
    combinationBadges: ["", "", "", "", ""],
    combinationDescriptions: ["可结合皮肤状态和管理目标，咨询射频与超声设备特点的组合。", "可综合皮肤困扰、预算和治疗范围进行咨询的提升组合。", "可根据双下巴、深层面颊或面颊松弛等困扰进行咨询的复合管理组合。", "可根据皮肤状态及紧致与皮肤管理目标一同考虑的组合。", "可一同咨询肤质、表情纹等个人皮肤困扰的组合。"],
    recommendTitle: "以下人群可考虑Thermage FLX",
    recommendations: ["希望在非手术方式下进行皮肤紧致管理者", "希望咨询面部、眼周或颈部紧致困扰者", "希望咨询毛孔、肤质等复合皮肤困扰者", "希望咨询治疗后是否适合当天恢复日常生活者", "希望根据个人皮肤状态制定提升方案者"],
    areasCaption: "Thermage FLX可治疗部位",
    starTitle: "基于皮肤状态，STAR皮肤科与您共同规划",
    starIntro: "STAR皮肤科会考量个人皮肤类型、脸型、困扰部位和管理目标，谨慎规划治疗部位与范围。",
    strengths: ["皮肤科专科医师\n诊疗", "20年以上\n临床经验", "一对一系统化\n个性化方案", "配备多种\n提升设备"],
    certificationTitle: "使用Thermage FLX原装治疗头",
    certificationText: "STAR皮肤科在治疗时使用一次性原装治疗头。",
    tipTitle: "按治疗部位选择的Thermage FLX治疗头",
    tips: [{ name: "全效治疗头 4.0cm²", area: "面部专用", description: "结合面部治疗范围和皮肤状态使用的治疗头。" }, { name: "眼周治疗头 0.25cm²", area: "眼周专用", description: "用于眼周等精细部位的专用治疗头。" }],
    directorCaption: "Thermage FLX临床顾问 曹时亨院长",
    ...EMPTY_VIDEO_COPY,
  },
  "zh-TW": {
    trustTitles: ["使用一次性原廠探頭", "FDA・MFDS許可設備", "皮膚科專科醫師診療"],
    trustSubtitles: ["每次療程前開封", "設備許可資訊", "依個人狀態規劃"],
    mobileControlUnitAlt: "",
    heroTitle: "透過射頻能量協助肌膚緊實管理的Thermage FLX",
    heroDescription: "釜山西面STAR皮膚科會依個人膚況，進行Thermage FLX諮詢與療程規劃。",
    whatTitle: "Thermage FLX是什麼療程？",
    whatParagraphs: ["Thermage FLX是透過向肌膚傳遞射頻（RF）能量，協助進行肌膚緊實管理的設備。療程方式會依部位與個人膚況，於諮詢後決定。", "療程會搭配冷卻與震動功能，探頭種類和療程範圍由醫療團隊依臉部、眼周、頸部等管理目的規劃。"],
    depthTitle: "射頻能量傳遞過程",
    depthText: "確認膚況後，在接觸面冷卻的同時傳遞射頻能量。詳細規劃與反應可能因個人狀態而異。",
    authTitle: "為何要確認Thermage FLX原廠探頭？",
    authParagraphs: ["Thermage FLX療程會依施作部位和範圍，確認探頭選擇及設備接觸狀態。療程前需要充分諮詢膚況與管理目標。", "STAR皮膚科於療程時使用一次性原廠探頭。"],
    authCaption: "附有識別標籤的Thermage FLX原廠探頭包裝",
    collagenTitle: "射頻能量後的膠原重塑過程",
    collagenStages: ["確認膚況與目標部位", "傳遞射頻能量", "個人化恢復過程"],
    collagenNote: "肌膚變化和維持時間會因個人膚況、療程範圍與規劃而異，應在醫療諮詢後決定。",
    processTitle: "Thermage FLX的三項特點",
    processDescriptions: ["以4.0cm²全效探頭規劃臉部療程範圍", "考量個人膚況規劃能量傳遞", "冷卻與震動功能有助於管理療程中的不適"],
    processNote: "施作部位、探頭和能量設定會在確認膚況與管理目標後，進行個人化規劃。",
    painTitle: "擔心Thermage FLX的疼痛管理嗎？",
    painOptions: ["麻醉藥膏", "局部麻醉注射", "舒眠麻醉"],
    painParagraphs: ["可依疼痛敏感度和療程範圍，於諮詢後選擇麻醉藥膏、局部麻醉注射或舒眠麻醉。", "包含舒眠管理在內的措施是否進行，需依個人狀態和醫療團隊判斷決定。療程前需要充分說明與諮詢。"],
    combinationTitle: "可與Thermage FLX一同考量的療程",
    combinationTitles: ["Thermage FLX + Ultherapy Prime", "Thermage FLX + Shurink Universe", "Thermage FLX + ONDA + V-RO", "Thermage FLX + Lumenis One + Rejuran", "Thermage FLX + 肌膚肉毒"],
    combinationBadges: ["", "", "", "", ""],
    combinationDescriptions: ["可依膚況與管理目標，諮詢射頻與超音波設備特性的組合。", "可一併考量肌膚困擾、預算與療程範圍進行諮詢的拉提組合。", "可依雙下巴、深層臉頰或雙頰鬆弛等困擾諮詢的複合管理組合。", "可依膚況及緊實、膚況管理目標一同考量的組合。", "可一同諮詢膚質、表情紋等個別肌膚困擾的組合。"],
    recommendTitle: "以下族群可考量Thermage FLX",
    recommendations: ["希望以非手術方式進行肌膚緊實管理者", "希望諮詢臉部、眼周或頸部緊實困擾者", "希望諮詢毛孔、膚質等複合肌膚困擾者", "希望諮詢療程後是否適合當日恢復日常生活者", "希望依個人膚況規劃拉提療程者"],
    areasCaption: "Thermage FLX可施作部位",
    starTitle: "以膚況為基礎，STAR皮膚科與您一同規劃",
    starIntro: "STAR皮膚科會考量個人膚質、臉型、困擾部位與管理目標，審慎規劃施作部位與範圍。",
    strengths: ["皮膚科專科醫師\n診療", "20年以上\n臨床經驗", "一對一系統化\n客製規劃", "備有多種\n拉提設備"],
    certificationTitle: "使用Thermage FLX原廠探頭",
    certificationText: "STAR皮膚科於療程時使用一次性原廠探頭。",
    tipTitle: "依部位選擇的Thermage FLX探頭",
    tips: [{ name: "全效探頭 4.0cm²", area: "臉部專用", description: "結合臉部療程範圍與膚況使用的探頭。" }, { name: "眼周探頭 0.25cm²", area: "眼周專用", description: "用於眼周等細緻部位的專用探頭。" }],
    directorCaption: "Thermage FLX臨床顧問 趙時享院長",
    ...EMPTY_VIDEO_COPY,
  },
};

export const THERMAGE_FLX_INFO_ROWS: Record<Lang, readonly { label: string; value: string }[]> = {
  ko: [
    { label: "시술 설명", value: "고주파(RF) 에너지를 활용해 피부 탄력 관리를 돕는 시술입니다." },
    { label: "적합한 대상", value: "얼굴·눈가·목 등 피부 탄력 고민을 상담하고 싶은 분" },
    { label: "효과 지속 기간", value: "약 1~2년 (개인 상태에 따라 다를 수 있음)" },
    { label: "시술 소요 시간", value: "약 45~90분 (부위와 범위에 따라 다름)" },
    { label: "회복 기간", value: "개인 상태에 따라 당일 일상 복귀 여부를 안내" },
    { label: "부작용·주의사항", value: "일시적인 붉음·열감·부기 등이 있을 수 있어 상담 후 결정" },
    { label: "권장 횟수·간격", value: "1~2회, 6~12개월 간격을 참고하되 상담 후 결정" },
  ],
  en: [
    { label: "What it is", value: "A treatment that uses radiofrequency energy to support skin-firmness care." },
    { label: "Who it may suit", value: "Those wishing to discuss firmness concerns of the face, eye area, or neck" },
    { label: "Effect duration", value: "About 1–2 years; this can vary by individual condition" },
    { label: "Treatment time", value: "About 45–90 minutes, depending on area and range" },
    { label: "Recovery", value: "Same-day return to daily activities is assessed according to individual condition" },
    { label: "Side effects & precautions", value: "Temporary redness, warmth, or swelling can occur; decide after consultation" },
    { label: "Recommended sessions & interval", value: "One to two sessions at 6–12-month intervals may be considered after consultation" },
  ],
  ja: [
    { label: "施術説明", value: "高周波（RF）エネルギーを活用し、肌のハリケアをサポートする施術です。" },
    { label: "適した方", value: "顔・目元・首などの肌のハリの悩みを相談したい方" },
    { label: "効果の持続", value: "約1〜2年（個人の状態により異なります）" },
    { label: "施術時間", value: "約45〜90分（部位と範囲により異なります）" },
    { label: "回復期間", value: "当日の生活復帰可否は個人の状態に応じてご案内します" },
    { label: "副作用・注意事項", value: "一時的な赤み・熱感・腫れが出ることがあり、相談後に決定します" },
    { label: "推奨回数・間隔", value: "1〜2回、6〜12か月間隔を目安に、相談後に決定します" },
  ],
  zh: [
    { label: "治疗说明", value: "利用射频（RF）能量，帮助进行皮肤紧致管理的治疗。" },
    { label: "适合人群", value: "希望咨询面部、眼周、颈部等紧致困扰者" },
    { label: "效果持续时间", value: "约1～2年（可能因个人状态而异）" },
    { label: "治疗所需时间", value: "约45～90分钟（因部位与范围而异）" },
    { label: "恢复期", value: "是否适合当天恢复日常生活，会根据个人状态说明" },
    { label: "副作用与注意事项", value: "可能出现暂时泛红、热感或肿胀，需在咨询后决定" },
    { label: "建议次数与间隔", value: "可参考1～2次、间隔6～12个月，具体在咨询后决定" },
  ],
  "zh-TW": [
    { label: "療程說明", value: "利用射頻（RF）能量，協助進行肌膚緊實管理的療程。" },
    { label: "適合對象", value: "希望諮詢臉部、眼周、頸部等緊實困擾者" },
    { label: "效果持續時間", value: "約1～2年（可能因個人狀態而異）" },
    { label: "療程所需時間", value: "約45～90分鐘（依部位與範圍而異）" },
    { label: "恢復期", value: "是否適合當日恢復日常生活，會依個人狀態說明" },
    { label: "副作用與注意事項", value: "可能出現暫時泛紅、熱感或腫脹，需於諮詢後決定" },
    { label: "建議次數與間隔", value: "可參考1～2次、間隔6～12個月，具體於諮詢後決定" },
  ],
};

export const THERMAGE_FLX_SEO: Record<Lang, { title: string; description: string }> = {
  ko: {
    title: "부산 써마지 FLX | 부산 서면 스타피부과",
    description: "부산 서면 스타피부과의 써마지 FLX 안내입니다. 얼굴·눈가·목 등 피부 탄력 관리 부위를 상담하며, 시술은 약 45~90분 소요될 수 있습니다. 개인 상태에 따라 당일 일상 복귀 여부를 안내합니다.",
  },
  en: {
    title: "Thermage FLX | STAR Dermatology, Seomyeon, Busan",
    description: "Thermage FLX at STAR Dermatology, Seomyeon, Busan. Discuss care for the face, eye area, and neck; treatment may take about 45–90 minutes. Same-day return to daily activities is assessed individually.",
  },
  ja: {
    title: "Thermage FLX | 釜山西面 STAR皮膚科",
    description: "釜山西面STAR皮膚科のThermage FLX施術案内。顔・目元・首などの肌のハリケアを相談し、施術は約45〜90分です。当日の生活復帰可否は個人の状態に応じてご案内します。",
  },
  zh: {
    title: "Thermage FLX | 釜山西面 STAR皮肤科",
    description: "釜山西面STAR皮肤科Thermage FLX治疗介绍。可咨询面部、眼周、颈部等皮肤紧致管理，治疗约需45～90分钟；是否适合当天恢复日常生活将根据个人状态说明。",
  },
  "zh-TW": {
    title: "Thermage FLX | 釜山西面 STAR皮膚科",
    description: "釜山西面STAR皮膚科Thermage FLX療程介紹。可諮詢臉部、眼周、頸部等肌膚緊實管理，療程約45～90分鐘；是否適合當日恢復日常生活會依個人狀態說明。",
  },
};
