/**
 * 예약 폼 공유 상수
 * - FORM_LABELS: 다국어 레이블
 * - CATEGORIES / TREATMENTS_BY_CATEGORY: 시술 목록 (한국어 고정, DB 기준)
 * - CLINIC_HOURS / HOLIDAYS: 진료시간 및 공휴일
 */

export const FORM_LABELS = {
  ko: {
    patientName: "환자명 *",
    patientNamePlaceholder: "이름을 입력해주세요",
    phone: "연락처 *",
    phonePlaceholder: "010-1234-5678",
    phoneIntlPlaceholder: "+82-10-1234-5678",
    category: "시술 카테고리 *",
    categoryPlaceholder: "선택해주세요",
    treatment: "시술명 *",
    treatmentPlaceholder: "선택해주세요",
    date: "희망 날짜 *",
    time: "희망 시간",
    timePlaceholder: "날짜를 먼저 선택해주세요",
    notes: "추가 사항",
    notesPlaceholder: "특별한 요청사항이 있으시면 입력해주세요",
    submit: "예약 신청",
    submitting: "예약 중...",
    restart: "처음부터 시작",
    reenter: "다시 입력",
    otpTitle: "비회원으로 예약하시려면 휴대폰 인증이 필요합니다.",
    otpSend: "인증번호 발송",
    otpSending: "발송 중...",
    otpLabel: "인증번호 *",
    otpPlaceholder: "6자리 인증번호 입력",
    otpVerify: "인증",
    otpVerifying: "인증 중...",
    otpVerifyMsg: "휴대폰으로 받은 인증번호를 입력해주세요.",
    confirmedMsg: "인증되었습니다. 예약 정보를 입력해주세요.",
    phoneInvalid: "올바른 휴대폰 번호 형식이 아닙니다. (010-1234-5678 형식)",
    phoneValid: "올바른 휴대폰 번호 형식입니다.",
    dateUnavailable: "예약 불가능한 날짜입니다. (당일, 일요일, 공휴일 제외)",
    validationCategory: "시술 카테고리와 시술명을 선택해주세요.",
    validationDate: "희망 날짜를 선택해주세요.",
    validationPhone: "연락처를 입력해주세요.",
    validationPhoneFormat: "올바른 휴대폰 번호를 입력해주세요. (010-1234-5678 또는 01012345678 형식)",
    successMsg: "예약이 신청되었습니다. 곧 연락드리겠습니다.",
    errorMsg: "예약 신청 실패: ",
    otpSentMsg: "인증번호가 발송되었습니다. 휴대폰을 확인해주세요.",
    otpSentError: "OTP 발송 실패: ",
    otpVerifiedMsg: "인증되었습니다.",
    otpVerifyError: "인증 실패: ",
    otpTimerLabel: "유효 시간",
    otpExpiredMsg: "인증번호가 만료되었습니다. 다시 발송해주세요.",
    otpResend: "재발송",
    otpResending: "재발송 중...",
  },
  en: {
    patientName: "Patient Name *",
    patientNamePlaceholder: "Enter your name",
    phone: "Phone Number *",
    phonePlaceholder: "+82-10-1234-5678",
    phoneIntlPlaceholder: "+82-10-1234-5678",
    category: "Treatment Category *",
    categoryPlaceholder: "Please select",
    treatment: "Treatment Name *",
    treatmentPlaceholder: "Please select",
    date: "Preferred Date *",
    time: "Preferred Time",
    timePlaceholder: "Please select a date first",
    notes: "Additional Notes",
    notesPlaceholder: "Any special requests or concerns",
    submit: "Request Booking",
    submitting: "Submitting...",
    restart: "Start Over",
    reenter: "Re-enter",
    otpTitle: "Phone verification is required for guest booking.",
    otpSend: "Send Verification Code",
    otpSending: "Sending...",
    otpLabel: "Verification Code *",
    otpPlaceholder: "Enter 6-digit code",
    otpVerify: "Verify",
    otpVerifying: "Verifying...",
    otpVerifyMsg: "Enter the verification code sent to your phone.",
    confirmedMsg: "Verified. Please enter your booking details.",
    phoneInvalid: "Invalid phone number format.",
    phoneValid: "Valid phone number.",
    dateUnavailable: "This date is unavailable. (Same day, Sunday, and holidays excluded)",
    validationCategory: "Please select a treatment category and name.",
    validationDate: "Please select a preferred date.",
    validationPhone: "Please enter your phone number.",
    validationPhoneFormat: "Please enter a valid phone number.",
    successMsg: "Your booking request has been submitted. We will contact you shortly.",
    errorMsg: "Booking failed: ",
    otpSentMsg: "Verification code sent.",
    otpSentError: "Failed to send OTP: ",
    otpVerifiedMsg: "Verified successfully.",
    otpVerifyError: "Verification failed: ",
    otpTimerLabel: "Time remaining",
    otpExpiredMsg: "The verification code has expired. Please request a new one.",
    otpResend: "Resend",
    otpResending: "Sending...",
  },
  ja: {
    patientName: "お名前 *",
    patientNamePlaceholder: "お名前を入力してください",
    phone: "電話番号 *",
    phonePlaceholder: "+82-10-1234-5678",
    phoneIntlPlaceholder: "+82-10-1234-5678",
    category: "施術カテゴリ *",
    categoryPlaceholder: "選択してください",
    treatment: "施術名 *",
    treatmentPlaceholder: "選択してください",
    date: "ご希望の日付 *",
    time: "ご希望の時間",
    timePlaceholder: "まず日付を選択してください",
    notes: "備考",
    notesPlaceholder: "ご要望があればご記入ください",
    submit: "予約を申し込む",
    submitting: "送信中...",
    restart: "最初からやり直す",
    reenter: "再入力",
    otpTitle: "ゲスト予約には電話番号の認証が必要です。",
    otpSend: "認証コードを送信",
    otpSending: "送信中...",
    otpLabel: "認証コード *",
    otpPlaceholder: "6桁の認証コードを入力",
    otpVerify: "認証する",
    otpVerifying: "認証中...",
    otpVerifyMsg: "お電話に届いた認証コードを入力してください。",
    confirmedMsg: "認証されました。予約情報を入力してください。",
    phoneInvalid: "電話番号の形式が正しくありません。",
    phoneValid: "正しい電話番号形式です。",
    dateUnavailable: "この日付は予約できません。（当日・日曜・祝日を除く）",
    validationCategory: "施術カテゴリと施術名を選択してください。",
    validationDate: "ご希望の日付を選択してください。",
    validationPhone: "電話番号を入力してください。",
    validationPhoneFormat: "正しい電話番号を入力してください。",
    successMsg: "ご予約のお申し込みを受け付けました。まもなくご連絡いたします。",
    errorMsg: "予約の申し込みに失敗しました: ",
    otpSentMsg: "認証コードを送信しました。",
    otpSentError: "OTP送信失敗: ",
    otpVerifiedMsg: "認証されました。",
    otpVerifyError: "認証失敗: ",
    otpTimerLabel: "有効時間",
    otpExpiredMsg: "認証コードの有効期限が切れました。再送信してください。",
    otpResend: "再送信",
    otpResending: "送信中...",
  },
  zh: {
    patientName: "患者姓名 *",
    patientNamePlaceholder: "请输入您的姓名",
    phone: "联系电话 *",
    phonePlaceholder: "+82-10-1234-5678",
    phoneIntlPlaceholder: "+82-10-1234-5678",
    category: "治疗类别 *",
    categoryPlaceholder: "请选择",
    treatment: "治疗项目 *",
    treatmentPlaceholder: "请选择",
    date: "希望日期 *",
    time: "希望时间",
    timePlaceholder: "请先选择日期",
    notes: "备注",
    notesPlaceholder: "如有特殊要求请填写",
    submit: "提交预约",
    submitting: "提交中...",
    restart: "重新开始",
    reenter: "重新输入",
    otpTitle: "访客预约需要手机验证。",
    otpSend: "发送验证码",
    otpSending: "发送中...",
    otpLabel: "验证码 *",
    otpPlaceholder: "请输入6位验证码",
    otpVerify: "验证",
    otpVerifying: "验证中...",
    otpVerifyMsg: "请输入发送到您手机的验证码。",
    confirmedMsg: "验证成功。请填写预约信息。",
    phoneInvalid: "电话号码格式不正确。",
    phoneValid: "电话号码格式正确。",
    dateUnavailable: "该日期无法预约。（当天、周日及节假日除外）",
    validationCategory: "请选择治疗类别和项目。",
    validationDate: "请选择希望日期。",
    validationPhone: "请输入联系电话。",
    validationPhoneFormat: "请输入正确的电话号码。",
    successMsg: "预约申请已提交，我们将尽快与您联系。",
    errorMsg: "预约失败: ",
    otpSentMsg: "验证码已发送。",
    otpSentError: "OTP发送失败: ",
    otpVerifiedMsg: "验证成功。",
    otpVerifyError: "验证失败: ",
    otpTimerLabel: "有效时间",
    otpExpiredMsg: "验证码已过期，请重新发送。",
    otpResend: "重新发送",
    otpResending: "发送中...",
  },
} as const;

export type FormLabels = (typeof FORM_LABELS)[keyof typeof FORM_LABELS];

// 시술 카테고리 (한국어 고정 - 예약 DB 기준)
export const CATEGORIES = [
  { id: "1",  label: "Best 시술" },
  { id: "2",  label: "리프팅·탄력" },
  { id: "3",  label: "눈밑지방" },
  { id: "4",  label: "백반증" },
  { id: "5",  label: "색소·문신" },
  { id: "6",  label: "흉터·모공" },
  { id: "7",  label: "여드름" },
  { id: "8",  label: "홍조·혈관" },
  { id: "9",  label: "액취증·다한증" },
  { id: "10", label: "손·발톱무좀" },
  { id: "11", label: "건선·아토피" },
  { id: "12", label: "볼륨·부스터" },
  { id: "13", label: "보톡스·필러" },
];

export const TREATMENTS_BY_CATEGORY: Record<string, string[]> = {
  "1":  ["울써마지 리프팅 + 리쥬란", "프로파운드 RF 리프팅", "볼륨업 프로그램", "줄기세포 치료", "흉터 치료 프로그램", "홍조 치료 프로그램", "기미 치료 프로그램"],
  "2":  ["울쎄라피 프라임", "써마지 FLX", "세르프", "울쎄라", "프로파운드", "텐쎄라", "버츄RF", "슈링크 유니버스", "온다", "텐써마", "BBL 스킨타이트", "트리니티 리프토닝"],
  "3":  ["눈밑지방재배치", "런치타임 눈밑레이저"],
  "4":  ["백반증 치료 프로그램", "엑셀V+ 백반증 치료"],
  "5":  ["기미 치료 프로그램", "엑셀V+ 색소 치료", "문신 제거"],
  "6":  ["흉터 치료 프로그램", "여드름 흉터 치료", "패인 흉터 치료"],
  "7":  ["여드름 치료 프로그램", "여드름 흉터 치료", "여드름 관리"],
  "8":  ["홍조 치료 프로그램", "엑셀V+ 홍조 치료", "모세혈관 확장 치료"],
  "9":  ["액취증 치료", "다한증 치료", "미라드라이"],
  "10": ["손톱무좀 치료", "발톱무좀 치료", "레이저 무좀 치료"],
  "11": ["건선 치료", "아토피 치료", "가려움증 관리"],
  "12": ["볼륨업 프로그램", "스컬트라", "필러 시술", "지방이식"],
  "13": ["보톡스 시술", "필러 시술", "콤비네이션 시술"],
};

// 진료시간 (요일별, 0=일요일)
export const CLINIC_HOURS: Record<string, { start: number | null; end: number | null; name: string }> = {
  "0": { start: null, end: null, name: "일" },
  "1": { start: 10,   end: 19,   name: "월" },
  "2": { start: 10,   end: 19,   name: "화" },
  "3": { start: 10,   end: 19,   name: "수" },
  "4": { start: 10,   end: 19,   name: "목" },
  "5": { start: 10,   end: 19,   name: "금" },
  "6": { start: 9.5,  end: 15,   name: "토" },
};

// 공휴일 목록 (2026년 기준)
export const HOLIDAYS = [
  "2026-01-01", "2026-02-17", "2026-03-01", "2026-04-15",
  "2026-05-05", "2026-05-24", "2026-06-06", "2026-08-15",
  "2026-09-24", "2026-10-03", "2026-10-09", "2026-12-25",
];
